name: Unit tests RDMAgent
on:
  pull_request:
    branches: [ develop, main ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}

jobs:
  execute-unit-tests-on-pr:
    name: Execute unit tests in RDMAgent GTest suite
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
            set -e
            sh unit_test.sh
        

      - name: Upload test results to automatic test result management system
        if: github.repository_owner == 'rdkcentral'
        run: |
          git config --global --add safe.directory `pwd`
          gtest-json-result-push.py /tmp/RDMAgent_Gtest_Report https://rdkeorchestrationservice.apps.cloud.comcast.net/rdke_orchestration_api/push_unit_test_results `pwd`
